### ISSUE TITLE
python errors on qgis 3.14 on w10 - not working

### ISSUE THREAD

**Issue by johansanders** [qgist/workbench#11]
not working 
2020-09-16T12:32:08     WARNING    Traceback (most recent call last):
              File "C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3/python/plugins\workbench\qgist\workbench\core.py", line 199, in _connect_ui
              config = config,
              File "C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3/python/plugins\workbench\qgist\workbench\dtype_fsm.py", line 86, in __init__
              self.new_workbench(translate('global', 'user default'), mainwindow)
              File "C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3/python/plugins\workbench\qgist\workbench\dtype_fsm.py", line 141, in new_workbench
              config = self._config,
              File "C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3/python/plugins\workbench\qgist\workbench\dtype_workbench.py", line 314, in from_mainwindow
              mainwindow, QDockWidget
              File "C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3/python/plugins\workbench\qgist\workbench\dtype_workbench.py", line 244, in _get_uielements_from_mainwindow
              for uielement in mainwindow.findChildren(uielement_type)
              File "C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3/python/plugins\workbench\qgist\workbench\dtype_workbench.py", line 245, in 
              if get_parent(uielement).objectName() == 'QgisApp'
             AttributeError: 'NoneType' object has no attribute 'objectName'

**Comment by s-m-e** [comment]
This is unexpected. I need to spin up a Windows test system ... 

- Which minor version of 3.14 do you run? 3.14.0 or 3.14.1 ... 
- Are you running QGIS via OSGeo4W or did you install QGIS via its own stand-alone installer?

**Comment by johansanders** [comment]
Standalone installer with  customized profiles map


AttributeError: 'NoneType' object has no attribute 'objectName'
Traceback (most recent call last):
  File "C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3/python/plugins\workbench\qgist\workbench\core.py", line 199, in _connect_ui
    config = config,
  File "C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3/python/plugins\workbench\qgist\workbench\dtype_fsm.py", line 86, in __init__
    self.new_workbench(translate('global', 'user default'), mainwindow)
  File "C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3/python/plugins\workbench\qgist\workbench\dtype_fsm.py", line 141, in new_workbench
    config = self._config,
  File "C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3/python/plugins\workbench\qgist\workbench\dtype_workbench.py", line 314, in from_mainwindow
    mainwindow, QDockWidget
  File "C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3/python/plugins\workbench\qgist\workbench\dtype_workbench.py", line 244, in _get_uielements_from_mainwindow
    for uielement in mainwindow.findChildren(uielement_type)
  File "C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3/python/plugins\workbench\qgist\workbench\dtype_workbench.py", line 245, in
    if get_parent(uielement).objectName() == 'QgisApp'
AttributeError: 'NoneType' object has no attribute 'objectName'

Python versie: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
QGIS versie: 3.14.0-Pi Pi, 9f7028fd23
Python pad:
·                     C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3/python/plugins\clusterpoints
·                     C:/bbqgis_3/apps/qgis/./python
·                     C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3/python
·                     C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3/python/plugins
·                     C:/bbqgis_3/apps/qgis/./python/plugins
·                     C:\bbqgis_3\apps\Python37
·                     C:\bbqgis_3\apps\Python37\Scripts
·                     C:\bbqgis_3\bin\python37.zip
·                     C:\bbqgis_3\apps\Python37\DLLs
·                     C:\bbqgis_3\apps\Python37\lib
·                     C:\bbqgis_3\bin
·                     C:\Users\johan_sanders\AppData\Roaming\Python\Python37\site-packages
·                     C:\bbqgis_3\apps\Python37\lib\site-packages
·                     C:\bbqgis_3\apps\Python37\lib\site-packages\win32
·                     C:\bbqgis_3\apps\Python37\lib\site-packages\win32\lib
·                     C:\bbqgis_3\apps\Python37\lib\site-packages\Pythonwin
·                     C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3/python
·                     D:\eclipse\plugins\org.python.pydev.core_7.0.3.201811082356\pysrc
·                     C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3/python/plugins\geosys-plugin
·                     C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3\python\plugins
·                     C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3/python/plugins\go2streetview
·                     C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3\python\plugins\go2streetview\res
·                     C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3\python\plugins\kmltools\libs
·                     C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3\python\plugins\mmqgis/forms
·                     C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3/python/plugins\Polygons_Pile
·                     C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3/python/plugins\qgis2web
·                     C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3\python\plugins
·                     C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3/python/plugins\qgis_resource_sharing
·                     C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3\python\plugins\qgis_resource_sharing
·                     C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3\python\plugins\qgis_resource_sharing\ext_libs
·                     .
·                     C:\bbqgis_3\_mijnprofiel\profiles\bbqgis_3\python\plugins\QuickMultiAttributeEdit3/forms
C:/bbqgis_3/_mijnprofiel/profiles/bbqgis_3

Vriendelijke groeten
________________________________
Johan Sanders
Dienstverlening
Consulent Dienstbetoon
E johan.sanders@boerenbond.be<mailto:johan.sanders@boerenbond.be>
T (092) 43 88 31<tel:+3292438831>
M (0472) 81 03 36<tel:+32472810336>
Boerenbond & Landelijke Gilden
Kortrijksesteenweg 1144 J, 9051 Sint-Denijs-Westrem
http://www.boerenbond.be<http://www.boerenbond.be/>
http://www.landelijkegilden.be<http://www.landelijkegilden.be/>


Van: sme <notifications@github.com>
Verzonden: woensdag 16 september 2020 12:40
Aan: qgist/workbench <workbench@noreply.github.com>
CC: Johan Sanders <johan.sanders@boerenbond.be>; Author <author@noreply.github.com>
Onderwerp: Re: [qgist/workbench] python errors on qgis 3.14 on w10 - not working (#11)


This is unexpected. I need to spin up a Windows test system ...

  *   Which minor version of 3.14 do you run? 3.14.0 or 3.14.1 ...
  *   Are you running QGIS via OSGeo4W or did you install QGIS via its own stand-alone installer?
